name: CI Pipeline

on:
  push:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest
    environment: production
    env:
      IMAGE_NAME: aws-cicd-tutorial
      IMAGE_VERSION: latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        echo "${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:$IMAGE_VERSION"
    - name: Build the Docker image
      # run: docker build -t aws-cicd-tutorial .
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:$IMAGE_VERSION
    - name: Push to Dockerhub
      # run: docker push $DOCKER_USERNAME/aws-cicd-tutorial:latest
      run: docker push ${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:$IMAGE_VERSION
